CREATE TABLE `contractorApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`telegramId` varchar(100),
	`fullAddress` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`postcode` varchar(20) NOT NULL,
	`hasRightToWork` boolean NOT NULL,
	`passportNumber` varchar(50),
	`passportPhotoUrl` text,
	`hasPublicLiability` boolean DEFAULT false,
	`cisRegistrationStatus` enum('registered','not_registered') NOT NULL,
	`cisNumber` varchar(50),
	`utrNumber` varchar(50),
	`hasValidCscsCard` boolean DEFAULT false,
	`bankName` varchar(100) NOT NULL,
	`accountHolderName` varchar(100) NOT NULL,
	`sortCode` varchar(20) NOT NULL,
	`accountNumber` varchar(20) NOT NULL,
	`emergencyContactName` varchar(100) NOT NULL,
	`emergencyContactPhone` varchar(50) NOT NULL,
	`emergencyContactRelationship` varchar(50) NOT NULL,
	`primaryTrade` varchar(100) NOT NULL,
	`yearsOfExperience` varchar(50) NOT NULL,
	`hasOwnTools` boolean DEFAULT false,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`adminNotes` text,
	`cisRate` int,
	`approvedBy` int,
	`approvedAt` timestamp,
	`contractorId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contractorApplications_id` PRIMARY KEY(`id`)
);
